export const loremIpsum = `Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.`;

export const services = [
  {
    id: 1,
    name: "Full Wedding Planning & Coordination",
    desc: "From the first idea to the final toast, we guide you through every step of your wedding journey – venue selection, vendor management, timeline creation, and on-the-day coordination. With our five-star hospitality background, every detail is executed with care, precision, and grace to ensure your celebration unfolds effortlessly.",
  },
  {
    id: 2,
    name: "Wedding Styling & Creative Direction",
    desc: "Your wedding should feel like you. We craft bespoke design concepts inspired by your story – from mood boards and colour palettes to tablestyling and floral direction. Each element is curated to create a cohesive atmosphere that reflects your personality, style, and emotion.",
  },
  {
    id: 3,
    name: "Private Villa Weddings",
    desc: "Drawing from our expertise in Bali's villa industry, we design and manage intimate celebrations in exclusive private villas. Each setting is thoughtfully transformed into an elegant, comfortable, and romantic space – ideal for couples seeking privacy and authenticity.",
  },
  {
    id: 4,
    name: "Intimate Weddings & Elopements",
    desc: "For those who believe less can mean more – we create intimate, heartfelt celebrations that focus on connection and meaning. Whether it's just the two of you or a few cherished guests, your day will feel personal, timeless, and beautifully yours.",
  },
  {
    id: 5,
    name: "Concept & Design Consultation",
    desc: "For couples who already have some plans but need creative direction, we offer personalized consultations. From visual storytelling and spatial flow to bespoke design sketches, we help refine your ideas into a cohesive and elevated concept.",
  },
  {
    id: 6,
    name: "Event & Table Styling",
    desc: "We believe beauty is found in the details. Our team curates table settings, décor elements, and visual compositions that harmonize with your overall theme – turning each celebration into an artful expression of style and atmosphere.",
  },
  {
    id: 7,
    name: "Destination Guest Management (Optional Add-On)",
    desc: "Ensure your guests experience Bali at its best. From accommodation arrangements to airport transfers and itinerary planning, our team handles the details so everyone enjoys a seamless and memorable stay.",
  },
];

export const locations = [
  "All",
  "Uluwatu",
  "Ubud",
  "Sanur",
  "Canggu",
  "Seminyak",
];

export const venues = [
  {
    id: 1,
    name: "Uma Kalai — Private Villa Wedding Venue in Bali",
    city: "Ubud",
    province: "Bali",
    capacity: "40 pax",
    image:
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790204/uma-kalai1_q6u09z.png",
    images: [
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790204/uma-kalai1_q6u09z.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790210/uma-kalai2_j4rlhk.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790217/uma-kalai4_xdtnio.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790218/uma-kalai5_gkky0a.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790193/uma-kalai26_kf9gpy.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790147/uma-kalai11_jgnuaq.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790172/uma-kalai18_kykyuj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790218/uma-kalai3_w68pph.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790203/uma-kalai28_gdnamm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790193/uma-kalai27_yybd0g.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790191/uma-kalai24_maithl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790188/uma-kalai22_ba3r6h.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790181/uma-kalai25_av7hki.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790171/uma-kalai20_od5ytz.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790170/uma-kalai16_mwhuq2.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790164/uma-kalai17_qnljau.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790161/uma-kalai14_wzyrbg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790158/uma-kalai13_w3mnz3.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790149/uma-kalai7_lylz6m.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790144/uma-kalai10_ahxwdu.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790142/uma-kalai8_umjdqw.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790219/uma-kalai30_rfoc2q.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790217/uma-kalai29_nxkucb.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790208/uma-kalai31_drhkwf.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790192/uma-kalai23_u8dv17.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790188/uma-kalai21_uj7l62.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790172/uma-kalai19_zzplb0.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790168/uma-kalai15_noiyih.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790153/uma-kalai6_rgueiz.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790154/uma-kalai9_ziyzxc.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1761790148/uma-kalai12_sjhnab.png",
    ],
    description:
      "Hidden in the lush hills of Sayan, Uma Kalai Ubud is a luxury private villa wedding venue where romance meets nature. Set against panoramic rice field views, this exclusive estate offers an intimate setting for small weddings and elopements of up to 40 guests. Blending Balinese heritage with refined modern elegance, Uma Kalai invites couples to celebrate love surrounded by breathtaking landscapes, curated wellness experiences, and the soulful energy of Ubud — creating a truly timeless Bali wedding experience.",
  },
  {
    id: 2,
    name: "The Legian Seminyak — Timeless Beachfront Elegance",
    city: "Seminyak",
    province: "Bali",
    capacity: "60 pax",
    image:
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360303/Hero-1_ztm3oo.png",
    images: [
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360303/Hero-1_ztm3oo.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360197/Hero-2_fnt428.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360310/Hero-3_de6rvv.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360304/Hero-4_pwpsd0.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360301/Hero-5_xwklja.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360302/Hero-6_ndtxwp.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360302/Hero-7_tw9hcm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360235/Wedding-1_bwha1o.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360258/Wedding-2_gk56aj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360268/Wedding-3_hz1oba.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360263/Wedding-4_nfsyaf.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360273/Wedding-5_uriggr.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360270/Wedding-6_hgfefl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360276/Wedding-7_ryn4cb.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360279/Wedding-8_u7zykg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360285/Wedding-9_nv39bc.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360228/Wedding-10_ozdebj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360195/Wedding-11_mqawhq.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360241/Wedding-12_jgxydz.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360241/Wedding-13_y0ahlo.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360252/Wedding-14_a4y266.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360240/Wedding-15_hwtayu.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360245/Wedding-16_gll5nr.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360252/Wedding-17_jpaebg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360259/Wedding-18_fmritj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360254/Wedding-19_uzkwxb.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360263/Wedding-20_s7dvef.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360201/Facilities-1_qvzmxl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360282/Facilities-2_jne3bl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360288/Facilities-3_shtlvw.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360282/Facilities-4_jzhpoh.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360185/Facilities-5_u5x05y.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360276/Facilities-6_ywmgfg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360304/Facilities-7_iywhz5.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360290/Facilities-8_qvcwma.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360310/Facilities-9_jkitst.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360222/Room-1_qfvqel.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360216/Room-2_t0jndz.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360208/Room-3_jybei2.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360216/Room-4_astz82.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360229/Room-5_dmasrc.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360209/Room-6_cvcgnk.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360222/Room-7_kbzowe.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360217/Room-8_dqs9ms.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360194/Room-9_sjajj3.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360190/Lifestyle-1_dgneye.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360192/Lifestyle-2_ysjdxm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360203/Lifestyle-3_alr99q.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360186/Lifestyle-4_l1fppm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360190/Lifestyle-5_kfb1t5.png",
    ],
    description:
      "Nestled along Bali’s most coveted beachfront, The Legian Seminyak, Bali embodies understated luxury and timeless charm. Fusing iconic architecture with authentic Balinese heritage, this legendary hotel offers an intimate haven where every celebration feels both refined and personal.\nDesigned by world-renowned architects and visionaries of hospitality, The Legian creates bespoke wedding experiences for up to 60 guests — each moment defined by heartfelt service, exquisite cuisine, and breathtaking ocean views.\nExchange vows on the golden sands of Seminyak Beach or within lush tropical gardens, accompanied by the soft rhythm of a Balinese Gamelan orchestra. Whether an intimate beach ceremony or a private celebration at The Beach House, every detail is seamlessly curated to create a celebration that’s felt, lived, and remembered.",
  },
  // {
  //   id: 3,
  //   name: "Griya Agung Ballroom",
  //   city: "Sanur",
  //   province: "Bali",
  //   capacity: "1000 pax",
  //   image: "/images/venue3.png",
  //   images: [
  //     "/images/venue3.png",
  //     "/images/venue4.png",
  //     "/images/venue1.png",
  //     "/images/venue2.png",
  //   ],
  //   description:
  //     "Griya Agung Ballroom is an elegant and spacious venue perfect for grand celebrations. With its sophisticated design and state-of-the-art facilities, it can accommodate large wedding parties with ease.",
  // },
  // {
  //   id: 4,
  //   name: "Tirtha Uluwatu",
  //   city: "Uluwatu",
  //   province: "Bali",
  //   capacity: "500 pax",
  //   image: "/images/venue4.png",
  //   images: [
  //     "/images/venue4.png",
  //     "/images/venue1.png",
  //     "/images/venue2.png",
  //     "/images/venue3.png",
  //   ],
  //   description:
  //     "Perched on the cliffs of Uluwatu, Tirtha offers breathtaking ocean views and a romantic setting for your special day. The venue combines luxury with natural beauty.",
  // },
  // {
  //   id: 5,
  //   name: "Renaissance Bali Uluwatu Resort & Spa",
  //   city: "Uluwatu",
  //   province: "Bali",
  //   capacity: "300 pax",
  //   image: "/images/venue5.png",
  //   images: [
  //     "/images/venue5.png",
  //     "/images/venue1.png",
  //     "/images/venue2.png",
  //     "/images/venue3.png",
  //   ],
  //   description:
  //     "Renaissance Bali Uluwatu Resort & Spa offers world-class amenities and stunning views. The resort features multiple event spaces suitable for intimate gatherings or grand celebrations.",
  // },
  // {
  //   id: 6,
  //   name: "Villa The Palm House",
  //   city: "Canggu",
  //   province: "Bali",
  //   capacity: "1000 pax",
  //   image: "/images/venue6.png",
  //   images: [
  //     "/images/venue6.png",
  //     "/images/venue1.png",
  //     "/images/venue2.png",
  //     "/images/venue3.png",
  //   ],
  //   description:
  //     "Villa The Palm House is a modern and stylish venue in the heart of Canggu. With its contemporary design and spacious layout, it's perfect for trendy and sophisticated celebrations.",
  // },
  // {
  //   id: 7,
  //   name: "Alila Villas Uluwatu",
  //   city: "Uluwatu",
  //   province: "Bali",
  //   capacity: "200 pax",
  //   image: "/images/venue1.png",
  //   images: [
  //     "/images/venue1.png",
  //     "/images/venue2.png",
  //     "/images/venue3.png",
  //     "/images/venue4.png",
  //   ],
  //   description:
  //     "Alila Villas Uluwatu combines luxury with intimacy. The villa features private pools, lush gardens, and personalized service for an unforgettable wedding experience.",
  // },
  // {
  //   id: 8,
  //   name: "The Mulia Resort",
  //   city: "Seminyak",
  //   province: "Bali",
  //   capacity: "800 pax",
  //   image: "/images/venue2.png",
  //   images: [
  //     "/images/venue2.png",
  //     "/images/venue3.png",
  //     "/images/venue4.png",
  //     "/images/venue1.png",
  //   ],
  //   description:
  //     "The Mulia Resort is a five-star luxury destination offering world-class facilities and impeccable service. Perfect for grand celebrations with stunning beachfront views.",
  // },
  // {
  //   id: 9,
  //   name: "Four Seasons Resort Bali",
  //   city: "Ubud",
  //   province: "Bali",
  //   capacity: "120 pax",
  //   image: "/images/venue3.png",
  //   images: [
  //     "/images/venue3.png",
  //     "/images/venue4.png",
  //     "/images/venue1.png",
  //     "/images/venue2.png",
  //   ],
  //   description:
  //     "Four Seasons Resort Bali offers an exclusive and intimate setting for your wedding. With its lush surroundings and personalized service, it's ideal for smaller, more intimate celebrations.",
  // },
  // {
  //   id: 10,
  //   name: "W Bali - Seminyak",
  //   city: "Seminyak",
  //   province: "Bali",
  //   capacity: "400 pax",
  //   image: "/images/venue4.png",
  //   images: [
  //     "/images/venue4.png",
  //     "/images/venue1.png",
  //     "/images/venue2.png",
  //     "/images/venue3.png",
  //   ],
  //   description:
  //     "W Bali - Seminyak is a trendy and vibrant venue perfect for modern celebrations. With its stylish design and beachfront location, it offers a unique and memorable setting.",
  // },
];
