export const loremIpsum = `Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.`;

export const services = [
  {
    id: 1,
    name: "Full Wedding Planning & Coordination",
    desc: "From the first idea to the final toast, we guide you through every step of your wedding journey – venue selection, vendor management, timeline creation, and on-the-day coordination. With our five-star hospitality background, every detail is executed with care, precision, and grace to ensure your celebration unfolds effortlessly.",
  },
  {
    id: 2,
    name: "Wedding Styling & Creative Direction",
    desc: "Your wedding should feel like you. We craft bespoke design concepts inspired by your story – from mood boards and colour palettes to tablestyling and floral direction. Each element is curated to create a cohesive atmosphere that reflects your personality, style, and emotion.",
  },
  {
    id: 3,
    name: "Private Villa Weddings",
    desc: "Drawing from our expertise in Bali's villa industry, we design and manage intimate celebrations in exclusive private villas. Each setting is thoughtfully transformed into an elegant, comfortable, and romantic space – ideal for couples seeking privacy and authenticity.",
  },
  {
    id: 4,
    name: "Intimate Weddings & Elopements",
    desc: "For those who believe less can mean more – we create intimate, heartfelt celebrations that focus on connection and meaning. Whether it's just the two of you or a few cherished guests, your day will feel personal, timeless, and beautifully yours.",
  },
  {
    id: 5,
    name: "Concept & Design Consultation",
    desc: "For couples who already have some plans but need creative direction, we offer personalized consultations. From visual storytelling and spatial flow to bespoke design sketches, we help refine your ideas into a cohesive and elevated concept.",
  },
  {
    id: 6,
    name: "Event & Table Styling",
    desc: "We believe beauty is found in the details. Our team curates table settings, décor elements, and visual compositions that harmonize with your overall theme – turning each celebration into an artful expression of style and atmosphere.",
  },
  {
    id: 7,
    name: "Destination Guest Management (Optional Add-On)",
    desc: "Ensure your guests experience Bali at its best. From accommodation arrangements to airport transfers and itinerary planning, our team handles the details so everyone enjoys a seamless and memorable stay.",
  },
];

export const locations = [
  "All",
  "Uluwatu",
  "Ubud",
  "Sanur",
  "Canggu",
  "Seminyak",
];

export const venues = [
  {
    id: 1,
    name: "Uma Kalai",
    slogan: "Private Villa Wedding Venue in Bali",
    city: "Ubud",
    province: "Bali",
    capacity: "40 pax",
    price: 95000000,
    image:
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412265/Hero-1_hsslnr.png",
    images: [
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412265/Hero-1_hsslnr.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412261/Hero-2_ywj1jm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412265/Hero-3_or6ske.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412262/Hero-4_c9kodj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412046/Wedding-1_fgmshs.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412109/Wedding-2_swb4bc.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412124/Wedding-3_zwpaho.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412113/Wedding-4_bxqbsa.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412135/Wedding-5_t7twn5.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412133/Wedding-6_wsgjk6.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412126/Wedding-7_wadlje.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412165/Wedding-8_bfxhyn.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412170/Wedding-9_jcsc84.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412107/Wedding-10_cnhyag.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412047/Wedding-11_p3emmd.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412087/Wedding-12_yqx5yi.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412085/Wedding-13_dnoo7w.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412068/Wedding-14_nixpbj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412049/Wedding-15_w3afos.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412177/Facilities-1_ymxt1s.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412208/Facilities-2_j7gby2.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412223/Facilities-3_w2lbdr.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412214/Facilities-4_c2cg5o.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412229/Facilities-5_fqydzj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412230/Facilities-6_tzhdt2.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412225/Facilities-7_j6xuzy.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412246/Facilities-8_dnhz4q.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412259/Facilities-9_blro6n.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412176/Facilities-10_qscvgy.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412189/Facilities-11_etukal.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412174/Facilities-12_tnwula.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411958/Room-1_s2zgqg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412001/Room-2_ljn2ej.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411990/Room-3_tc2wnl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412020/Room-4_laf6fd.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412018/Room-5_ye8acx.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412028/Room-6_qjb7ib.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412032/Room-7_epagy3.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411953/Room-8_blsxaq.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412046/Room-9_zjuyyb.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411978/Room-10_xameee.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411994/Room-11_srasqm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762412005/Room-12_uhkprj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411955/Lifestyle-1_mruckr.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411962/Lifestyle-2_ubs2hs.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411955/Lifestyle-3_gch7p8.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411965/Lifestyle-4_qnhyal.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411988/Lifestyle-5_p7kd7u.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411975/Lifestyle-6_xh8lms.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762411992/Lifestyle-7_etyjwi.png",
    ],
    description:
      "Hidden in the lush hills of Sayan, Uma Kalai Ubud is a luxury private villa wedding venue where romance meets nature. Set against panoramic rice field views, this exclusive estate offers an intimate setting for small weddings and elopements of up to 40 guests. Blending Balinese heritage with refined modern elegance, Uma Kalai invites couples to celebrate love surrounded by breathtaking landscapes, curated wellness experiences, and the soulful energy of Ubud — creating a truly timeless Bali wedding experience.",
  },
  {
    id: 2,
    name: "The Legian Seminyak",
    slogan: "Timeless Beachfront Elegance",
    city: "Seminyak",
    province: "Bali",
    capacity: "60 pax",
    price: 0,
    image:
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360303/Hero-1_ztm3oo.png",
    images: [
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360303/Hero-1_ztm3oo.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360197/Hero-2_fnt428.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360310/Hero-3_de6rvv.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360304/Hero-4_pwpsd0.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360301/Hero-5_xwklja.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360302/Hero-6_ndtxwp.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360302/Hero-7_tw9hcm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360235/Wedding-1_bwha1o.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360258/Wedding-2_gk56aj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360268/Wedding-3_hz1oba.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360263/Wedding-4_nfsyaf.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360273/Wedding-5_uriggr.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360270/Wedding-6_hgfefl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360276/Wedding-7_ryn4cb.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360279/Wedding-8_u7zykg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360285/Wedding-9_nv39bc.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360228/Wedding-10_ozdebj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360195/Wedding-11_mqawhq.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360241/Wedding-12_jgxydz.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360241/Wedding-13_y0ahlo.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360252/Wedding-14_a4y266.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360240/Wedding-15_hwtayu.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360245/Wedding-16_gll5nr.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360252/Wedding-17_jpaebg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360259/Wedding-18_fmritj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360254/Wedding-19_uzkwxb.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360263/Wedding-20_s7dvef.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360201/Facilities-1_qvzmxl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360282/Facilities-2_jne3bl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360288/Facilities-3_shtlvw.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360282/Facilities-4_jzhpoh.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360185/Facilities-5_u5x05y.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360276/Facilities-6_ywmgfg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360304/Facilities-7_iywhz5.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360290/Facilities-8_qvcwma.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360310/Facilities-9_jkitst.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360222/Room-1_qfvqel.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360216/Room-2_t0jndz.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360208/Room-3_jybei2.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360216/Room-4_astz82.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360229/Room-5_dmasrc.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360209/Room-6_cvcgnk.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360222/Room-7_kbzowe.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360217/Room-8_dqs9ms.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360194/Room-9_sjajj3.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360190/Lifestyle-1_dgneye.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360192/Lifestyle-2_ysjdxm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360203/Lifestyle-3_alr99q.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360186/Lifestyle-4_l1fppm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762360190/Lifestyle-5_kfb1t5.png",
    ],
    description:
      "Nestled along Bali’s most coveted beachfront, The Legian Seminyak, Bali embodies understated luxury and timeless charm. Fusing iconic architecture with authentic Balinese heritage, this legendary hotel offers an intimate haven where every celebration feels both refined and personal.\nDesigned by world-renowned architects and visionaries of hospitality, The Legian creates bespoke wedding experiences for up to 60 guests — each moment defined by heartfelt service, exquisite cuisine, and breathtaking ocean views.\nExchange vows on the golden sands of Seminyak Beach or within lush tropical gardens, accompanied by the soft rhythm of a Balinese Gamelan orchestra. Whether an intimate beach ceremony or a private celebration at The Beach House, every detail is seamlessly curated to create a celebration that’s felt, lived, and remembered.",
  },
  {
    id: 3,
    name: "The Sanctoo",
    slogan: "A Serene & Elegant Wedding Venue",
    city: "Ubud",
    province: "Bali",
    capacity: "120 pax",
    price: 25150000,
    image:
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945250/Hero-2_pqkyqg.png",
    images: [
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945250/Hero-2_pqkyqg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945247/Hero-1_pfuhns.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945251/Hero-3_srju4t.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945255/Hero-4_dd6hvy.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945256/Hero-5_sese0t.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945253/Hero-6_x4fgvz.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945273/Wedding-1_nbmcae.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945288/Wedding-2_fwaure.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945299/Wedding-3_keaptq.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945289/Wedding-4_jjkb78.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945289/Wedding-5_ryewg0.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945300/Wedding-6_hwlqdm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945296/Wedding-7_sgkvwu.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945297/Wedding-9_r0n31b.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945274/Wedding-10_dfm0vg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945277/Wedding-11_lxsjdn.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945280/Wedding-12_hixhba.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945280/Wedding-13_ybtevc.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945281/Wedding-14_fgfyaa.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945281/Wedding-15_esxvvj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945283/Wedding-16_most5t.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945285/Wedding-17_ebg8fx.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945288/Wedding-18_y5yxwp.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945262/Room-1_ckf8hb.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945253/Room-2_sizvns.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945257/Room-3_huk6jg.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945262/Room-4_seqcbm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945264/Room-5_gpzczl.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945272/Room-6_hqyjgx.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945270/Room-7_hjeyva.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945273/Room-8_yxlknj.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945272/Room-9_su9ufs.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945266/Room-10_kgvn2u.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945264/Room-11_ybook7.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945308/Facilities-1_cilm3y.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945310/Facilities-2_ujkbbu.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945316/Facilities-3_cpbctc.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945314/Facilities-4_ayjx4z.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945319/Facilities-5_kruotm.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945317/Facilities-6_diwmsy.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945316/Facilities-7_dqzcmq.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945316/Facilities-8_ryq1eq.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945324/Facilities-9_mzjw9u.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945305/Facilities-11_ctuf4q.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945298/Facilities-12_dsyrny.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945299/Facilities-13_prhpjh.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945307/Facilities-14_o3b0qk.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945308/Facilities-15_jqxs6i.png",
      "https://res.cloudinary.com/dzerxindp/image/upload/v1762945264/Lifestyle-1_vlnj7n.png",
    ],
    description:
      "Escape the ordinary and embrace the extraordinary with a wedding at Sanctoo Suites and Villas. Our serene setting, limited to 120 guests,provides an intimate and tranquil backdrop for your special day. With a focus on personalized service and seamless coordination, we create a truly unforgettable wedding experience that blendselegance with effortless grace. Experience a truly unforgettable wedding dinner at Sanctoo Suites and Villas. Our talented decorators are dedicated to fulfilling the bride's every wish, creating a captivating ambiance with stunning floral arrangements, elegant table settings, and captivating lighting. Whether you prefer the grandeur of long tables or the intimacy of round tables, we will tailor your wedding feast to create a truly magical experience.",
  },
];
